name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        env:
          ARM_CLIENT_ID: ${{ secrets.clientId }}
          ARM_CLIENT_SECRET: ${{ secrets.clientSecret }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.subscriptionId }}
          ARM_TENANT_ID: ${{ secrets.tenantId }}
        run: terraform apply -auto-approve
